FROM postgres:13
MAINTAINER Herwig Bogaert

RUN apt-get update \
    && apt-get install -y file socat \
    && rm -rf /var/lib/apt/lists/*

RUN chown postgres /docker-entrypoint-initdb.d

ENV RecoveryArea /recovery_area
ENV RecoverySocket "unix:/recovery_socket"

COPY load.sh /usr/local/bin/
COPY recover.sh /usr/local/bin/
RUN ln /usr/local/bin/recover.sh /usr/local/bin/hotstandby.sh


ARG RecoveryAreaGid=4
# local postgres user can write to the recovery socket and access the recovery area
RUN usermod -G $RecoveryAreaGid postgres

ARG CODESET=UTF-8
ARG LANG_TERR=en_US
RUN localedef -i ${LANG_TERR} -c -f ${CODESET} -A /usr/share/locale/locale.alias ${LANG_TERR}.${CODESET}

USER postgres
